package repository.util;

public enum RepositoryTypes {
    AUTHOR_REPOSITORY,
    MEMBER_REPOSITORY,
    PUBLISHER_REPOSITORY,
    CATEGORY_REPOSITORY,
    ADMIN_REPOSITORY,
    BORROW_BOOK_RECORDS_REPOSITORY,
    FINE_REPOSITORY
}
